### ISSUE TITLE
[BUG] Checking whether an index exists or not fails when the index is missing

### ISSUE THREAD

**Issue by DumboJet** [opensearch-project/opensearch-net#378]
### What is the bug?
Checking whether an index exists or not fails.

### How can one reproduce the bug?
Use this `OpenSearch.Client` code:
```
 var existsResponse = openSearchClient.Indices.Exists(documentsIndexName);
```
The above code, returns this for me when the index does not exist:
![image](https://github.com/opensearch-project/opensearch-net/assets/8492662/e14a428f-56e9-4cc1-b803-bfe26551e050)

```
Invalid OpenSearch.Client response built from a successful (404) low level call on HEAD: /documents?pretty=true&error_trace=true
# Audit trail of this API call:
 - [1] HealthyResponse: Node: https://opensearch.mydomain.local:9200/ Took: 00:00:32.1328917
# Request:
<Request stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>
# Response:

# TCP states:
  Established: 82
  TimeWait: 13
  CloseWait: 23

# ThreadPool statistics:
  Worker: 
    Busy: 12
    Free: 32755
    Min: 12
    Max: 32767
  IOCP: 
    Busy: 0
    Free: 1000
    Min: 12
    Max: 1000
```
When the index exists, it seems to be working OK.

### What is the expected behavior?
I would expect that `existsResponse.IsValid` is `true`.

### What is your host/environment?
Windows 11
OpenSearch.Client nuget version 1.5.0
OpenSearch Version: 2.9.0
OpenSearch Security Version: 2.9.0.0
